<img src="https://tradingcomdados.com/images/logotipo/logotipo-trading-com-dados.svg" width="300" align="left"/>

In [ ]:
!pip install yfinance
!pip install fundamentus

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.2.4-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 KB 1.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.3.5)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 KB 9.8 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (2022.7)
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 KB 11.9 MB/s eta 0:00:00
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.4.4)
Collecting cryptography>=3.3.2
  Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 52.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.8/dist-packages (from yfinance) (1.21.6)
Collecting requests>=2.26
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 4.5 MB/s eta 0:00:00
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 9.9 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from yfinance) (4.9.2)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: soupsieve, requests, html5lib, frozendict, cryptography, beautifulsoup4, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.11.1 cryptography-39.0.0 frozendict-2.3.4 html5lib-1.1 requests-2.28.2 soupsieve-2.3.2.post1 yfinance-0.2.4
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fundamentus
  Downloading fundamentus-0.2.0-py3-none-any.whl (13 kB)
Requirement already satisfied: lxml>=4.6.2 in /usr/local/lib/python3.8/dist-packages (from fundamentus) (4.9.2)
Requirement already satisfied: requests>=2.25.1 in /usr/local/lib/python3.8/dist-packages (from fundamentus) (2.28.2)
Collecting requests-cache>=0.5.2
  Downloading requests_cache-0.9.8-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.7/48.7 KB 3.7 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.8/dist-packages (from fundamentus) (1.3.5)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.8/dist-packages (from fundamentus) (0.8.10)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.5->fundamentus) (2022.7)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.5->fundamentus) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.5->fundamentus) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.25.1->fundamentus) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.25.1->fundamentus) (2.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.25.1->fundamentus) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.25.1->fundamentus) (2022.12.7)
Collecting cattrs>=22.2
  Downloading cattrs-22.2.0-py3-none-any.whl (35 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 14.4 MB/s eta 0:00:00
Collecting url-normalize>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.8/dist-packages (from requests-cache>=0.5.2->fundamentus) (22.2.0)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.8/dist-packages (from requests-cache>=0.5.2->fundamentus) (1.4.4)
Collecting exceptiongroup
  Downloading exceptiongroup-1.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1.5->fundamentus) (1.15.0)
Installing collected packages: urllib3, url-normalize, exceptiongroup, cattrs, requests-cache, fundamentus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed cattrs-22.2.0 exceptiongroup-1.1.0 fundamentus-0.2.0 requests-cache-0.9.8 url-normalize-1.4.3 urllib3-1.26.14

In [ ]:
import fundamentus
import numpy as np
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#Análise Fundamentalista

In [ ]:

df2 = fundamentus.get_resultado_raw()
df2

Multiples,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,EV/EBIT,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
papel,,,,,,,,,,,,,,,,,,,,
AALR3,21.41,-18.69,2.36,2.319,0.0000,0.963,-30.88,84.28,-2.49,106.32,21.83,0.0275,-0.1180,0.86,0.0132,-0.1263,10891400.0,1.072550e+09,0.85,0.0116
ABCB3,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.0000,0.1505,0.0,5.070730e+09,0.00,0.3047
ABCB4,19.78,5.86,0.88,0.000,0.0706,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.00,0.0000,0.1505,14417300.0,5.070730e+09,0.00,0.3047
ABEV3,13.53,16.27,2.36,2.697,0.0563,1.500,32.40,13.85,-23.80,12.81,9.50,0.1947,0.1715,1.19,0.1498,0.1452,490671000.0,9.017800e+10,0.03,0.1298
ABYA3,4.91,-214.80,1.76,2.055,0.0000,0.527,1.98,19.96,-2.75,33.67,33.67,0.1029,-0.0096,2.09,0.0278,-0.0082,0.0,2.920600e+08,1.31,0.1641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLMM4,15.85,5.09,0.95,0.324,0.0751,0.781,1.86,4.96,2.28,4.32,4.18,0.0653,0.0636,5.14,0.1832,0.1875,64183.0,6.050780e+08,0.02,0.2820
WMBY3,25.39,-19.30,2.87,0.836,0.0000,0.182,1.20,8.62,-1.50,25.02,25.02,0.0970,-0.0705,1.44,0.0239,-0.1486,0.0,2.124390e+08,6.51,-0.1448
WSON33,67.00,8.07,0.98,1.067,0.0000,0.400,13.41,2.42,-0.89,5.08,5.08,0.4414,0.1358,1.26,0.1836,0.1217,0.0,2.148530e+09,1.21,0.0523
YDUQ3,9.42,-61.47,0.96,0.645,0.0134,0.293,1.96,5.35,-0.72,12.95,5.66,0.1207,-0.0101,2.07,0.0669,-0.0157,44651000.0,3.024090e+09,1.89,0.0660
ZAMP3,5.07,-18.83,0.96,0.398,0.0000,0.350,9.51,18.89,-0.91,26.05,4.02,0.0211,-0.0211,1.17,0.0230,-0.0509,5706010.0,1.456990e+09,0.74,0.0956

In [ ]:
df = fundamentus.get_resultado()
df

Multiples,cotacao,pl,pvp,psr,dy,pa,pcg,pebit,pacl,evebit,evebitda,mrgebit,mrgliq,roic,roe,liqc,liq2m,patrliq,divbpatr,c5y
papel,,,,,,,,,,,,,,,,,,,,
AALR3,21.41,-18.69,2.36,2.319,0.0000,0.963,-30.88,84.28,-2.49,106.32,21.83,0.0275,-0.1180,0.0132,-0.1263,0.86,10891400.0,1.072550e+09,0.85,0.0116
ABCB3,0.00,0.00,0.00,0.000,0.0000,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.1505,0.00,0.0,5.070730e+09,0.00,0.3047
ABCB4,19.78,5.86,0.88,0.000,0.0706,0.000,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.1505,0.00,14417300.0,5.070730e+09,0.00,0.3047
ABEV3,13.53,16.27,2.36,2.697,0.0563,1.500,32.40,13.85,-23.80,12.81,9.50,0.1947,0.1715,0.1498,0.1452,1.19,490671000.0,9.017800e+10,0.03,0.1298
ABYA3,4.91,-214.80,1.76,2.055,0.0000,0.527,1.98,19.96,-2.75,33.67,33.67,0.1029,-0.0096,0.0278,-0.0082,2.09,0.0,2.920600e+08,1.31,0.1641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLMM4,15.85,5.09,0.95,0.324,0.0751,0.781,1.86,4.96,2.28,4.32,4.18,0.0653,0.0636,0.1832,0.1875,5.14,64183.0,6.050780e+08,0.02,0.2820
WMBY3,25.39,-19.30,2.87,0.836,0.0000,0.182,1.20,8.62,-1.50,25.02,25.02,0.0970,-0.0705,0.0239,-0.1486,1.44,0.0,2.124390e+08,6.51,-0.1448
WSON33,67.00,8.07,0.98,1.067,0.0000,0.400,13.41,2.42,-0.89,5.08,5.08,0.4414,0.1358,0.1836,0.1217,1.26,0.0,2.148530e+09,1.21,0.0523
YDUQ3,9.42,-61.47,0.96,0.645,0.0134,0.293,1.96,5.35,-0.72,12.95,5.66,0.1207,-0.0101,0.0669,-0.0157,2.07,44651000.0,3.024090e+09,1.89,0.0660
ZAMP3,5.07,-18.83,0.96,0.398,0.0000,0.350,9.51,18.89,-0.91,26.05,4.02,0.0211,-0.0211,0.0230,-0.0509,1.17,5706010.0,1.456990e+09,0.74,0.0956

In [ ]:
#setor = fundamentus.list_papel_setor(7)
setor = ['AMER3','MGLU3','VIIA3']

In [ ]:
df2.query('index in @setor')

Multiples,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,EV/EBIT,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
papel,,,,,,,,,,,,,,,,,,,,
AMER3,0.71,14.94,0.04,0.023,0.8767,0.014,0.05,0.53,-0.06,10.63,4.05,0.0431,0.0015,2.24,0.0361,0.0029,335980000.0,1.470560e+10,1.41,0.4703
MGLU3,3.82,-69.66,2.39,0.726,0.0000,0.717,3.41,30.03,-5.79,35.90,16.27,0.0242,-0.0104,1.58,0.0340,-0.0343,605656000.0,1.080530e+10,0.66,0.2794
VIIA3,2.27,-24.19,0.66,0.120,0.0000,0.107,-1.03,1.70,-0.27,5.49,3.61,0.0707,-0.0050,0.81,0.0830,-0.0272,194024000.0,5.505000e+09,1.69,0.0475

##Indicadores de Lucratividade / Operacionais

1) Margem EBIT 

2) Margem Líquida 

3) ROIC 

4) ROE 

5) Dividend Yeld 

6)CAGR - Crescimento de receita dos últimos 5 anos

In [ ]:
df.query('index in @setor').loc[:,['mrgebit','mrgliq', 'roic', 'roe', 'dy', 'c5y']]

Multiples  mrgebit  mrgliq    roic     roe      dy     c5y
papel
AMER3       0.0431  0.0015  0.0361  0.0029  0.8767  0.4703
MGLU3       0.0242 -0.0104  0.0340 -0.0343  0.0000  0.2794
VIIA3       0.0707 -0.0050  0.0830 -0.0272  0.0000  0.0475

In [ ]:
ind_luc = df.query('index in @setor').loc[:,['mrgebit','mrgliq', 'roic', 'roe', 'dy', 'c5y']]

##Indicadores de Preço & Valor

1)P/L 

2)P/VPA = Preço Ação/(PL/N ações)

3)EV/EBIT = EV - MarketCap + (div bruta - caixa)
 
4)EV/EBITDA

In [ ]:
ind_valor = df.query('index in @setor').loc[:,['pl', 'pvp', 'evebit', 'evebitda']]
ind_valor

Multiples     pl   pvp  evebit  evebitda
papel
AMER3      14.94  0.04   10.63      4.05
MGLU3     -69.66  2.39   35.90     16.27
VIIA3     -24.19  0.66    5.49      3.61

##Indicador de liquidez

- Liquidez_Corrente = Ativo Circulante/Passivo Circulante

In [ ]:
ind_liq = df2.query('index in @setor').loc[:,['Liq. Corr.']]

#Endividamento

- Divida Bruta/Patrimonio Liquido

In [ ]:
end = df.query('index in @setor').loc[:,['divbpatr']]
end

Multiples  divbpatr
papel
AMER3          1.41
MGLU3          0.66
VIIA3          1.69

##Informações da empresa

In [ ]:
ativo = yf.Ticker('AMER3.SA')

In [ ]:
#Campos confiáveis para esse ativo
#Net Income - Lucro Líquido
#Income Before Tax - Lucro antes do imposto de renda
#Selling General Administrative (SG&A) Despesas Operacionais
#Gross Profit - Lucro Bruto
#Income Tax Expense - Lucro antes do imposto de renda 
#Total Revenue - Total de Receita
#Cost Of Revenue - Custo da Receita

dre = ativo.get_financials(freq='quarterly')
dre

,2022-09-30,2022-06-30,2022-03-31,2021-12-31
TotalRevenue,5434936000.0,6696747000.0,6765190000.0,9091542000.0
OperatingRevenue,5434936000.0,6696747000.0,6765190000.0,9091542000.0
CostOfRevenue,3703863000.0,4607459000.0,4701251000.0,6393402000.0
GrossProfit,1731073000.0,2089288000.0,2063939000.0,2698140000.0
OperatingExpense,1646700000.0,1784603000.0,1782437000.0,2208059000.0
SellingGeneralAndAdministration,1630228000.0,1737685000.0,1899921000.0,2111918000.0
GeneralAndAdministrativeExpense,632949000.0,663542000.0,586665000.0,646907000.0
SellingAndMarketingExpense,997279000.0,1074143000.0,1313256000.0,1465011000.0
OtherOperatingExpenses,16472000.0,46918000.0,-117484000.0,96141000.0
OperatingIncome,84373000.0,304685000.0,281502000.0,490081000.0
NetNonOperatingInterestIncomeExpense,-612574000.0,-555039000.0,-462751000.0,-290673000.0
InterestIncomeNonOperating,187084000.0,138233000.0,117336000.0,211078000.0
InterestExpenseNonOperating,767570000.0,678358000.0,562344000.0,516989000.0
TotalOtherFinanceCost,32088000.0,14914000.0,17743000.0,-15238000.0
PretaxIncome,-526709000.0,-247596000.0,-179883000.0,204575000.0
TaxProvision,-315158000.0,-149691000.0,-42552000.0,-285101000.0
NetIncomeCommonStockholders,-211551000.0,-97905000.0,-137331000.0,489676000.0
NetIncome,-211551000.0,-97905000.0,-137331000.0,489676000.0
NetIncomeIncludingNoncontrollingInterests,-211551000.0,-97905000.0,-137331000.0,489676000.0
NetIncomeContinuousOperations,-211551000.0,-97905000.0,-137331000.0,489676000.0
OtherunderPreferredStockDividend,0.0,0.0,0.0,0.0
DilutedNIAvailtoComStockholders,-211551000.0,-97905000.0,-137331000.0,489676000.0
BasicEPS,NaN,NaN,-0.1549,NaN
DilutedEPS,NaN,NaN,-0.1549,NaN
BasicAverageShares,NaN,NaN,886477000.0,NaN
DilutedAverageShares,NaN,NaN,886477000.0,NaN
TotalOperatingIncomeAsReported,NaN,NaN,-281502000.0,NaN
TotalExpenses,5350563000.0,6392062000.0,6483688000.0,8601461000.0
NetIncomeFromContinuingAndDiscontinuedOperation,-211551000.0,-97905000.0,-137331000.0,489676000.0
NormalizedIncome,-211551000.0,-97905000.0,-137331000.0,489676000.0
InterestIncome,187084000.0,138233000.0,117336000.0,211078000.0
InterestExpense,767570000.0,678358000.0,562344000.0,516989000.0
NetInterestIncome,-612574000.0,-555039000.0,-462751000.0,-290673000.0
EBIT,240861000.0,430762000.0,382461000.0,721564000.0
ReconciledCostOfRevenue,3703863000.0,4607459000.0,4701251000.0,6393402000.0
ReconciledDepreciation,484301000.0,493961000.0,497832000.0,482974000.0
NetIncomeFromContinuingOperationNetMinorityInterest,-211551000.0,-97905000.0,-137331000.0,489676000.0
NormalizedEBITDA,725162000.0,924723000.0,880293000.0,1204538000.0
TaxRateForCalcs,0.4,0.4,0.23,0.34
TaxEffectOfUnusualItems,0.0,0.0,0.0,0.0

In [ ]:
dre = pd.DataFrame(dre)
dre = dre/1000
dre = dre[dre.columns[::-1]]
dre

,2021-12-31,2022-03-31,2022-06-30,2022-09-30
TotalRevenue,9091542.0,6765190.0,6696747.0,5434936.0
OperatingRevenue,9091542.0,6765190.0,6696747.0,5434936.0
CostOfRevenue,6393402.0,4701251.0,4607459.0,3703863.0
GrossProfit,2698140.0,2063939.0,2089288.0,1731073.0
OperatingExpense,2208059.0,1782437.0,1784603.0,1646700.0
SellingGeneralAndAdministration,2111918.0,1899921.0,1737685.0,1630228.0
GeneralAndAdministrativeExpense,646907.0,586665.0,663542.0,632949.0
SellingAndMarketingExpense,1465011.0,1313256.0,1074143.0,997279.0
OtherOperatingExpenses,96141.0,-117484.0,46918.0,16472.0
OperatingIncome,490081.0,281502.0,304685.0,84373.0
NetNonOperatingInterestIncomeExpense,-290673.0,-462751.0,-555039.0,-612574.0
InterestIncomeNonOperating,211078.0,117336.0,138233.0,187084.0
InterestExpenseNonOperating,516989.0,562344.0,678358.0,767570.0
TotalOtherFinanceCost,-15238.0,17743.0,14914.0,32088.0
PretaxIncome,204575.0,-179883.0,-247596.0,-526709.0
TaxProvision,-285101.0,-42552.0,-149691.0,-315158.0
NetIncomeCommonStockholders,489676.0,-137331.0,-97905.0,-211551.0
NetIncome,489676.0,-137331.0,-97905.0,-211551.0
NetIncomeIncludingNoncontrollingInterests,489676.0,-137331.0,-97905.0,-211551.0
NetIncomeContinuousOperations,489676.0,-137331.0,-97905.0,-211551.0
OtherunderPreferredStockDividend,0.0,0.0,0.0,0.0
DilutedNIAvailtoComStockholders,489676.0,-137331.0,-97905.0,-211551.0
BasicEPS,NaN,-0.000155,NaN,NaN
DilutedEPS,NaN,-0.000155,NaN,NaN
BasicAverageShares,NaN,886477.0,NaN,NaN
DilutedAverageShares,NaN,886477.0,NaN,NaN
TotalOperatingIncomeAsReported,NaN,-281502.0,NaN,NaN
TotalExpenses,8601461.0,6483688.0,6392062.0,5350563.0
NetIncomeFromContinuingAndDiscontinuedOperation,489676.0,-137331.0,-97905.0,-211551.0
NormalizedIncome,489676.0,-137331.0,-97905.0,-211551.0
InterestIncome,211078.0,117336.0,138233.0,187084.0
InterestExpense,516989.0,562344.0,678358.0,767570.0
NetInterestIncome,-290673.0,-462751.0,-555039.0,-612574.0
EBIT,721564.0,382461.0,430762.0,240861.0
ReconciledCostOfRevenue,6393402.0,4701251.0,4607459.0,3703863.0
ReconciledDepreciation,482974.0,497832.0,493961.0,484301.0
NetIncomeFromContinuingOperationNetMinorityInterest,489676.0,-137331.0,-97905.0,-211551.0
NormalizedEBITDA,1204538.0,880293.0,924723.0,725162.0
TaxRateForCalcs,0.00034,0.00023,0.0004,0.0004
TaxEffectOfUnusualItems,0.0,0.0,0.0,0.0

##Balanço

In [ ]:
ativo.get_cash_flow(freq='quarterly')

,2022-09-30,2022-06-30,2022-03-31,2021-12-31
OperatingCashFlow,-1701047000.0,154831000.0,-562313000.0,1492342000.0
NetIncomeFromContinuingOperations,-211551000.0,-97905000.0,-137331000.0,489676000.0
DepreciationAndAmortization,484301000.0,493961000.0,497832000.0,482974000.0
Depreciation,796614000.0,181648000.0,497832000.0,482974000.0
DeferredTax,-315158000.0,-149691000.0,-42552000.0,-285101000.0
ProvisionandWriteOffofAssets,-43894000.0,-10462000.0,-9763000.0,-27923000.0
OtherNonCashItems,760049000.0,622696000.0,272293000.0,497476000.0
ChangeInWorkingCapital,-2186319000.0,70158000.0,-990351000.0,1051650000.0
ChangeInReceivables,-823158000.0,767881000.0,1445695000.0,-850565000.0
ChangeInInventory,-446863000.0,550633000.0,-627828000.0,658811000.0
ChangeInPrepaidAssets,4104000.0,15666000.0,-9799000.0,661000.0
ChangeInPayable,-578764000.0,-1790314000.0,-1316681000.0,933083000.0
ChangeInAccruedExpense,40466000.0,-4682000.0,5807000.0,-78895000.0
ChangeInOtherCurrentAssets,35031000.0,251933000.0,-306019000.0,-26137000.0
ChangeInOtherCurrentLiabilities,-417135000.0,279041000.0,-181526000.0,414692000.0
InterestPaidCFO,-164461000.0,-755651000.0,-134016000.0,-688451000.0
TaxesRefundPaid,-4553000.0,-1791000.0,-3354000.0,-11150000.0
InvestingCashFlow,-740229000.0,-693800000.0,-444392000.0,-1922292000.0
NetPPEPurchaseAndSale,-106162000.0,-143236000.0,-134712000.0,-153557000.0
PurchaseOfPPE,-106162000.0,-143236000.0,-134712000.0,-153557000.0
NetIntangiblesPurchaseAndSale,-363474000.0,-407769000.0,-365161000.0,-486689000.0
PurchaseOfIntangibles,-363474000.0,-407769000.0,-365161000.0,-486689000.0
NetBusinessPurchaseAndSale,-64272000.0,-44718000.0,-71206000.0,-1828829000.0
PurchaseOfBusiness,-64272000.0,-44718000.0,-71206000.0,-1996895000.0
SaleOfBusiness,NaN,NaN,NaN,168066000.0
NetInvestmentPurchaseAndSale,-206921000.0,-98677000.0,126687000.0,546783000.0
SaleOfInvestment,NaN,-98677000.0,126687000.0,546783000.0
DividendsReceivedCFI,600000.0,NaN,NaN,NaN
FinancingCashFlow,4271183000.0,1161997000.0,158843000.0,-1243085000.0
NetIssuancePaymentsOfDebt,4406163000.0,1382169000.0,916167000.0,-1048554000.0
NetLongTermDebtIssuance,4406163000.0,1382169000.0,916167000.0,-1048554000.0
LongTermDebtIssuance,4555797000.0,1417173000.0,1149311000.0,9757000.0
LongTermDebtPayments,-149634000.0,-35004000.0,-233144000.0,-1058311000.0
NetCommonStockIssuance,27819000.0,-17523000.0,-271012000.0,52933000.0
CommonStockIssuance,27819000.0,190000.0,300570000.0,52921000.0
CommonStockPayments,0.0,-17713000.0,-571582000.0,12000.0
CashDividendsPaid,0.0,-32100000.0,-301105000.0,NaN
EndCashPosition,4311961000.0,2482054000.0,1859026000.0,2706888000.0
ChangesInCash,1829907000.0,623028000.0,-847862000.0,-1673035000.0
BeginningCashPosition,2482054000.0,1859026000.0,2706888000.0,4379923000.0
CapitalExpenditure,-469636000.0,-551005000.0,-499873000.0,-640246000.0
IssuanceOfCapitalStock,27819000.0,190000.0,300570000.0,52921000.0
IssuanceOfDebt,4555797000.0,1417173000.0,1149311000.0,9757000.0
RepaymentOfDebt,-149634000.0,-35004000.0,-233144000.0,-1058311000.0
RepurchaseOfCapitalStock,0.0,-17713000.0,-571582000.0,12000.0
FreeCashFlow,-2170683000.0,-396174000.0,-1062186000.0,852096000.0

In [ ]:
bal = ativo.get_balance_sheet(freq='quarterly')
bal

,2022-09-30,2022-06-30,2022-03-31,2021-12-31
TotalAssets,47084128000.0,43364028000.0,43817888000.0,44518812000.0
CurrentAssets,22433417000.0,19325374000.0,20401253000.0,21912888000.0
CashCashEquivalentsAndShortTermInvestments,8594893000.0,6567487000.0,5910294000.0,6931068000.0
CashAndCashEquivalents,4311961000.0,2482054000.0,1859026000.0,2706888000.0
CashFinancial,278480000.0,268655000.0,249624000.0,313037000.0
...,...,...,...,...
TotalDebt,24007104000.0,18829069000.0,17494706000.0,15926072000.0
NetDebt,16478917000.0,13040606000.0,12275230000.0,9633863000.0
ShareIssued,909774507.0,907116900.0,907111040.0,909632767.0
OrdinarySharesNumber,901420597.0,898762981.0,899856947.0,904048936.0
TreasurySharesNumber,8353910.0,8353919.0,7254093.0,5583831.0

In [ ]:
#Total Assets - Total do ativo
#Total Stockholder Equity - Patrimônio Líquido

balanco = pd.DataFrame(bal)
balanco = balanco/1000
balanco = balanco[balanco.columns[::-1]]
balanco

,2021-12-31,2022-03-31,2022-06-30,2022-09-30
TotalAssets,44518812.0,43817888.0,43364028.0,47084128.0
CurrentAssets,21912888.0,20401253.0,19325374.0,22433417.0
CashCashEquivalentsAndShortTermInvestments,6931068.0,5910294.0,6567487.0,8594893.0
CashAndCashEquivalents,2706888.0,1859026.0,2482054.0,4311961.0
CashFinancial,313037.0,249624.0,268655.0,278480.0
...,...,...,...,...
TotalDebt,15926072.0,17494706.0,18829069.0,24007104.0
NetDebt,9633863.0,12275230.0,13040606.0,16478917.0
ShareIssued,909632.767,907111.04,907116.9,909774.507
OrdinarySharesNumber,904048.936,899856.947,898762.981,901420.597
TreasurySharesNumber,5583.831,7254.093,8353.919,8353.91

In [ ]:
dre

,2021-12-31,2022-03-31,2022-06-30,2022-09-30
TotalRevenue,9091542.0,6765190.0,6696747.0,5434936.0
OperatingRevenue,9091542.0,6765190.0,6696747.0,5434936.0
CostOfRevenue,6393402.0,4701251.0,4607459.0,3703863.0
GrossProfit,2698140.0,2063939.0,2089288.0,1731073.0
OperatingExpense,2208059.0,1782437.0,1784603.0,1646700.0
SellingGeneralAndAdministration,2111918.0,1899921.0,1737685.0,1630228.0
GeneralAndAdministrativeExpense,646907.0,586665.0,663542.0,632949.0
SellingAndMarketingExpense,1465011.0,1313256.0,1074143.0,997279.0
OtherOperatingExpenses,96141.0,-117484.0,46918.0,16472.0
OperatingIncome,490081.0,281502.0,304685.0,84373.0
NetNonOperatingInterestIncomeExpense,-290673.0,-462751.0,-555039.0,-612574.0
InterestIncomeNonOperating,211078.0,117336.0,138233.0,187084.0
InterestExpenseNonOperating,516989.0,562344.0,678358.0,767570.0
TotalOtherFinanceCost,-15238.0,17743.0,14914.0,32088.0
PretaxIncome,204575.0,-179883.0,-247596.0,-526709.0
TaxProvision,-285101.0,-42552.0,-149691.0,-315158.0
NetIncomeCommonStockholders,489676.0,-137331.0,-97905.0,-211551.0
NetIncome,489676.0,-137331.0,-97905.0,-211551.0
NetIncomeIncludingNoncontrollingInterests,489676.0,-137331.0,-97905.0,-211551.0
NetIncomeContinuousOperations,489676.0,-137331.0,-97905.0,-211551.0
OtherunderPreferredStockDividend,0.0,0.0,0.0,0.0
DilutedNIAvailtoComStockholders,489676.0,-137331.0,-97905.0,-211551.0
BasicEPS,NaN,-0.000155,NaN,NaN
DilutedEPS,NaN,-0.000155,NaN,NaN
BasicAverageShares,NaN,886477.0,NaN,NaN
DilutedAverageShares,NaN,886477.0,NaN,NaN
TotalOperatingIncomeAsReported,NaN,-281502.0,NaN,NaN
TotalExpenses,8601461.0,6483688.0,6392062.0,5350563.0
NetIncomeFromContinuingAndDiscontinuedOperation,489676.0,-137331.0,-97905.0,-211551.0
NormalizedIncome,489676.0,-137331.0,-97905.0,-211551.0
InterestIncome,211078.0,117336.0,138233.0,187084.0
InterestExpense,516989.0,562344.0,678358.0,767570.0
NetInterestIncome,-290673.0,-462751.0,-555039.0,-612574.0
EBIT,721564.0,382461.0,430762.0,240861.0
ReconciledCostOfRevenue,6393402.0,4701251.0,4607459.0,3703863.0
ReconciledDepreciation,482974.0,497832.0,493961.0,484301.0
NetIncomeFromContinuingOperationNetMinorityInterest,489676.0,-137331.0,-97905.0,-211551.0
NormalizedEBITDA,1204538.0,880293.0,924723.0,725162.0
TaxRateForCalcs,0.00034,0.00023,0.0004,0.0004
TaxEffectOfUnusualItems,0.0,0.0,0.0,0.0

In [ ]:
fig = make_subplots(rows=9,
                    cols=2,
                    row_heights=[5,5,5,5,5,5,5,5,5],
                    column_widths=[3,3],
                    subplot_titles=('Receita Bruta', 'Lucro Líquido', 'Dívida CP', 'Dívida LP',
                                    'Capital de Giro','Divida Líquida',
                                    'Margem EBITDA', 'Margem Líquida', 'ROIC', 'ROE',
                                    'Div Bruta/PL', 'CAGR 5Y', 'Preço/Lucro', 'P/VP',
                                    'EV/EBIT', 'EV/EBITDA', 'Liquidez Corrente', 'Div Yeld'),
                    shared_xaxes=False)
fig.add_trace(go.Scatter(name='Receita_bruta', x=dre.columns, y=dre.loc['OperatingRevenue'], mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=1, col=1)
fig.add_trace(go.Scatter(name='Receita_liquida', x=dre.columns, y=dre.loc['NetIncome'],mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=1, col=2)


fig.add_trace(go.Scatter(name='Divida_CP', x=balanco.columns, y=balanco.loc['CurrentDebt'],mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=2, col=1)
fig.add_trace(go.Scatter(name='Divida_CP', x=balanco.columns, y=balanco.loc['LongTermDebt'],mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=2, col=2)

fig.add_trace(go.Scatter(name='WC', x=balanco.columns, y=balanco.loc['WorkingCapital'],mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=3, col=1)
fig.add_trace(go.Scatter(name='Divida_liquida', x=balanco.columns, y=balanco.loc['NetDebt'],mode='lines+markers',marker_size=15,marker_symbol='diamond'), row=3, col=2)

fig.add_trace(go.Bar(name='Margem_Ebtida', x=ind_luc.index, y=ind_luc['mrgebit']), row=4, col=1)
fig.add_trace(go.Bar(name='Margem_Liquida', x=ind_luc.index, y=ind_luc['mrgliq']), row=4, col=2)
fig.add_trace(go.Bar(name='ROIC', x=ind_luc.index, y=ind_luc['roic']), row=5, col=1)
fig.add_trace(go.Bar(name='ROE', x=ind_luc.index, y=ind_luc['roe']), row=5, col=2)

fig.add_trace(go.Bar(name='divbpatr', x=end.index, y=end['divbpatr']), row=6, col=1)
fig.add_trace(go.Bar(name='c5y', x=ind_luc.index, y=ind_luc['c5y']), row=6, col=2)

fig.add_trace(go.Bar(name='pl', x=ind_valor.index, 
                     y=ind_valor['pl']), row=7, col=1)
fig.add_trace(go.Bar(name='pvp', x=ind_valor.index, 
                     y=ind_valor['pvp']), row=7, col=2)

fig.add_trace(go.Bar(name='evebit', x=ind_valor.index, y=ind_valor['evebit']), row=8, col=1)
fig.add_trace(go.Bar(name='evebitda', x=ind_valor.index, y=ind_valor['evebitda']), row=8, col=2)

fig.add_trace(go.Bar(name='ind_liq', x=ind_liq.index, y=ind_liq['Liq. Corr.']), row=9, col=1)
fig.add_trace(go.Bar(name='dy', x=ind_luc.index, y=ind_luc['dy']), row=9, col=2)
fig.update_layout(title_text='<b>Avaliação Fundamentalista AMER3.SA<b>', 
                  template='plotly_dark',#template pré-definido da plotly
                  showlegend=False, #esconder ou mostrar legenda
                  height=1800, #altura
                  width=900) #largura
fig.show()

##Bônus - Cálculo do Giro do Ativo e Margem Líquida através do YF

- Giro do ativo: Total Revenue/Total Assets (todos na frequência anual)

In [ ]:
dre_a = ativo.get_financials(freq='yearly')
dre_a = pd.DataFrame(dre_a)
dre_a = dre_a/1000
dre_a = dre_a[dre_a.columns[::-1]]
dre_a

,2019-12-31,2020-12-31,2021-12-31
TotalRevenue,6661669.0,10124347.0,22695861.0
OperatingRevenue,6661669.0,10124347.0,22695861.0
CostOfRevenue,4756354.0,7247256.0,15934094.0
GrossProfit,1905315.0,2877091.0,6761767.0
OperatingExpense,1797946.0,2610924.0,5921787.0
SellingGeneralAndAdministration,891131.0,1490093.0,5764584.0
GeneralAndAdministrativeExpense,83679.0,118507.0,1774476.0
RentAndLandingFees,33404.0,22845.0,NaN
SellingAndMarketingExpense,807452.0,1371586.0,3990108.0
DepreciationAndAmortizationInIncomeStatement,519745.0,597909.0,NaN
DepreciationIncomeStatement,519745.0,597909.0,NaN
OtherOperatingExpenses,79270.0,75593.0,157203.0
OperatingIncome,107369.0,266167.0,839980.0
NetNonOperatingInterestIncomeExpense,-566351.0,-430176.0,-772404.0
InterestIncomeNonOperating,296746.0,186184.0,445245.0
InterestExpenseNonOperating,877910.0,575533.0,1206463.0
TotalOtherFinanceCost,-14813.0,40827.0,11186.0
PretaxIncome,-462696.0,-249603.0,-16236.0
TaxProvision,-144458.0,-38845.0,-560031.0
NetIncomeCommonStockholders,-318238.0,-210758.0,543795.0
NetIncome,-318238.0,-210758.0,543795.0
NetIncomeIncludingNoncontrollingInterests,-318238.0,-210758.0,543795.0
NetIncomeContinuousOperations,-318238.0,-210758.0,543795.0
MinorityInterests,0.0,0.0,NaN
OtherunderPreferredStockDividend,0.0,0.0,0.0
DilutedNIAvailtoComStockholders,-318238.0,-210758.0,543795.0
BasicEPS,-0.000673,-0.000393,0.000722
DilutedEPS,-0.000673,-0.000393,0.000716
BasicAverageShares,472598.482,536683.631,753548.08
DilutedAverageShares,479840.404,542123.417,759349.848
RentExpenseSupplemental,33404.0,22845.0,NaN
TotalExpenses,6554300.0,9858180.0,21855881.0
NetIncomeFromContinuingAndDiscontinuedOperation,-318238.0,-210758.0,543795.0
NormalizedIncome,-318238.0,-210758.0,543795.0
InterestIncome,296746.0,186184.0,445245.0
InterestExpense,877910.0,575533.0,1206463.0
NetInterestIncome,-566351.0,-430176.0,-772404.0
EBIT,415214.0,325930.0,1190227.0
ReconciledCostOfRevenue,4756354.0,7247256.0,15934094.0
ReconciledDepreciation,522704.0,601763.0,1300292.0
NetIncomeFromContinuingOperationNetMinorityInterest,-318238.0,-210758.0,543795.0
NormalizedEBITDA,937918.0,927693.0,2490519.0
TaxRateForCalcs,0.00031,0.00016,0.00034
TaxEffectOfUnusualItems,0.0,0.0,0.0