<img src="https://tradingcomdados.com/images/logotipo/logotipo-trading-com-dados.svg" width="300" align="left"/>

# **Avaliação Individual 1 da Mentoria**

Você tem a missão de desenvolver os códigos faltantes de um CASE atrelado a dividendos.
Dentro da lista de ativos que será apresentada para você, queremos que desenvolva uma análise de quais os maiores pagadores de dividendos.

In [2]:
#TASK 1 - Fazer o import das libs necessárias para análise (pandas, vectorbt e yfinance)

%pip install pandas
%pip install vectorbt
%pip install yfinance

Requirement already satisfied: pandas in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: vectorbt in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (0.24.5)
Requirement already satisfied: numpy>=1.16.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.23.5)
Requirement already satisfied: pandas in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.5.3)
Requirement already satisfied: scipy in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.10.1)
Requirement already satisfied: matplotlib in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (3.7.1)
Requirement already satisfied: plotly>=4.12.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (5.13.1)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (8.0.5)
Requirement already satisfied: dill in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (0.3.6)
Requirement already satisfied: tqdm in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (4.65.0)
Requirement already satisfied: dateparser in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.1.8)
Requirement already satisfied: imageio in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (2.26.1)
Requirement already satisfied: scikit-learn in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.2.2)
Requirement already satisfied: schedule in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.1.0)
Requirement already satisfied: requests in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (2.28.2)
Requirement already satisfied: pytz in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (2022.7.1)
Requirement already satisfied: mypy_extensions in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (1.0.0)
Requirement already satisfied: numba>=0.56.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from vectorbt) (0.56.4)
Requirement already satisfied: ipython>=6.1.0 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipywidgets>=7.0.0->vectorbt) (8.11.0)
Requirement already satisfied: jupyterlab-widgets~=3.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (3.0.6)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipywidgets>=7.0.0->vectorbt) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.0.0->vectorbt) (4.0.6)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from numba>=0.56.0->vectorbt) (0.39.1)
Requirement already satisfied: setuptools in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from numba>=0.56.0->vectorbt) (58.1.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from plotly>=4.12.0->vectorbt) (8.2.2)
Requirement already satisfied: tzlocal in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from dateparser->vectorbt) (4.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from dateparser->vectorbt) (2023.3.23)
Requirement already satisfied: python-dateutil in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from dateparser->vectorbt) (2.8.2)
Requirement already satisfied: pillow>=8.3.2 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from imageio->vectorbt) (9.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (23.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (4.39.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->vectorbt) (1.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests->vectorbt) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests->vectorbt) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests->vectorbt) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests->vectorbt) (1.26.14)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->vectorbt) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->vectorbt) (1.2.0)
Requirement already satisfied: colorama in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from tqdm->vectorbt) (0.4.6)
Requirement already satisfied: stack-data in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.6.2)
Requirement already satisfied: jedi>=0.16 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.18.2)
Requirement already satisfied: decorator in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (5.1.1)
Requirement already satisfied: pickleshare in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (3.0.38)
Requirement already satisfied: pygments>=2.4.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (2.14.0)
Requirement already satisfied: backcall in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\rubem\appdata\roaming\python\python310\site-packages (from ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.1.6)
Requirement already satisfied: six>=1.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil->dateparser->vectorbt) (1.16.0)
Requirement already satisfied: tzdata in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from tzlocal->dateparser->vectorbt) (2022.6)
Requirement already satisfied: pytz-deprecation-shim in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from tzlocal->dateparser->vectorbt) (0.1.0.post0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\rubem\appdata\roaming\python\python310\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.6)
Requirement already satisfied: pure-eval in c:\users\rubem\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (0.2.2)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (2.2.1)
Requirement already satisfied: executing>=1.2.0 in c:\users\rubem\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.0.0->vectorbt) (1.2.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: yfinance in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (0.2.12)
Requirement already satisfied: pandas>=1.3.0 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: numpy>=1.16.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (1.23.5)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: pytz>=2022.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2022.7.1)
Requirement already satisfied: cryptography>=3.3.2 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (39.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (4.11.2)
Requirement already satisfied: requests>=2.26 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (2.28.2)
Requirement already satisfied: lxml>=4.9.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (4.9.2)
Requirement already satisfied: html5lib>=1.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: cffi>=1.12 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->yfinance) (3.0.1)
Requirement already satisfied: pycparser in c:\users\rubem\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# TASK 2 - fazer o import dos pacotes necessários e ja instalados

import pandas as pd
import vectorbt as vbt
import yfinance as yf

In [4]:
tickers = ['ABEV3.SA', 'BBDC4.SA', 'ITUB4.SA','PETR4.SA', 'VALE3.SA', 'WEGE3.SA']

In [5]:
dividendos = vbt.YFData.download(tickers,
                                 start='2012-01-01',
                                 end='2021-12-31'
                                 ).get('Dividends')

dividendos

symbol,ABEV3.SA,BBDC4.SA,ITUB4.SA,PETR4.SA,VALE3.SA,WEGE3.SA
Date,,,,,,
2012-01-02 02:00:00+00:00,0.0,0.0000,0.005464,0.0000,0.0,0.0
2012-01-03 02:00:00+00:00,0.0,0.0057,0.000000,0.1773,0.0,0.0
2012-01-04 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2012-01-05 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2012-01-06 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
...,...,...,...,...,...,...
2021-12-23 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2021-12-27 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2021-12-28 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2021-12-29 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2021-12-30 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0

In [7]:
# TASK 3 -  Trazer as primeiras linhas do DF de dividendos

dividendos.head()

symbol,ABEV3.SA,BBDC4.SA,ITUB4.SA,PETR4.SA,VALE3.SA,WEGE3.SA
Date,,,,,,
2012-01-02 02:00:00+00:00,0.0,0.0000,0.005464,0.0000,0.0,0.0
2012-01-03 02:00:00+00:00,0.0,0.0057,0.000000,0.1773,0.0,0.0
2012-01-04 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2012-01-05 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0
2012-01-06 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0

In [8]:
# TASK 4 - Quantas variáveis são quantitativas e quantas são qualitativas usando um método?

dividendos.info()

"""dividendos

num_quant = 0
num_qual = 0
for col in dividendos.columns:
    if dividendos[col].dtype == 'float64' or dividendos[col].dtype == 'int64':
        num_quant += 1
    else:
        num_qual += 1

print(f'Número de variáveis quantitativas: {num_quant}')
print(f'Número de variáveis qualitativas: {num_qual}')"""

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2479 entries, 2012-01-02 02:00:00+00:00 to 2021-12-30 03:00:00+00:00
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ABEV3.SA  2479 non-null   float64
 1   BBDC4.SA  2479 non-null   float64
 2   ITUB4.SA  2479 non-null   float64
 3   PETR4.SA  2479 non-null   float64
 4   VALE3.SA  2479 non-null   float64
 5   WEGE3.SA  2479 non-null   float64
dtypes: float64(6)
memory usage: 200.1 KB

"dividendos\n\nnum_quant = 0\nnum_qual = 0\nfor col in dividendos.columns:\n    if dividendos[col].dtype == 'float64' or dividendos[col].dtype == 'int64':\n        num_quant += 1\n    else:\n        num_qual += 1\n\nprint(f'Número de variáveis quantitativas: {num_quant}')\nprint(f'Número de variáveis qualitativas: {num_qual}')"

In [9]:
#TASK 5 - Tem dado faltante?

dividendos_na = dividendos.isna().sum()
dividendos_null = dividendos.isnull().sum()

print(f'Total faltante: {dividendos_na.sum() + dividendos_null.sum()}')

Total faltante: 0

Qual o total pago por ação para cada ativo nesses 10 anos avaliados (2012 a 2021)?<p>
OBS: Métrica não muito útil já que depende do preço gasto em uma ação

In [11]:
# TASK 6 - Trazer a soma do total pago por ação e ordenação decrescente

dividendos_totais = dividendos.sum()

dividendos_totais.sort_values(ascending=False)

symbol
VALE3.SA    28.042675
ITUB4.SA    10.002561
PETR4.SA     9.368585
BBDC4.SA     7.533571
ABEV3.SA     6.222420
WEGE3.SA     1.697137
dtype: float64

In [12]:
# TASK 7 - Inserir uma coluna representando o "Ano" indicado pelo index usando strtime('%Y')

dividendos['Ano'] = pd.to_datetime(dividendos.index).strftime('%Y')

dividendos

symbol,ABEV3.SA,BBDC4.SA,ITUB4.SA,PETR4.SA,VALE3.SA,WEGE3.SA,Ano
Date,,,,,,,
2012-01-02 02:00:00+00:00,0.0,0.0000,0.005464,0.0000,0.0,0.0,2012
2012-01-03 02:00:00+00:00,0.0,0.0057,0.000000,0.1773,0.0,0.0,2012
2012-01-04 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2012
2012-01-05 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2012
2012-01-06 02:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2012
...,...,...,...,...,...,...,...
2021-12-23 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2021
2021-12-27 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2021
2021-12-28 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2021
2021-12-29 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2021
2021-12-30 03:00:00+00:00,0.0,0.0000,0.000000,0.0000,0.0,0.0,2021

Usar uma pivot table para visualizar os valores pagos por ano

In [16]:
# TASK 8 - use o método pd.pivot_table passando o df de dividendos com função de agregação de soma

tab_dinamica_dividendos = dividendos.pivot_table(index='Ano',aggfunc='sum')
tab_dinamica_dividendos

symbol  ABEV3.SA  BBDC4.SA  ITUB4.SA  PETR4.SA   VALE3.SA  WEGE3.SA
Ano
2012    0.476664  0.353056  0.523552  0.501700   2.261800  0.073076
2013    0.257176  0.336835  0.501785  0.386170   0.984650  0.100130
2014    0.593980  0.508545  0.536293  0.967200   1.889774  0.123241
2015    1.580000  0.652153  0.904846  0.000000   0.975371  0.150136
2016    0.640000  0.683637  1.063601  0.000000   0.166294  0.144652
2017    0.540000  0.706037  0.999266  0.000000   1.325484  0.137596
2018    0.550000  0.715273  1.970600  0.916563   1.968873  0.157902
2019    0.490600  2.060271  1.815860  0.942361   1.414364  0.170210
2020    0.413700  0.573779  0.780060  0.001359   2.407510  0.217194
2021    0.680300  0.943985  0.906698  5.653232  14.648555  0.423000

A classificação de dividendos depende não apenas do valor nominal pago, mas do preço de cada ação naquele momento.

In [22]:
# TASK 9 - Buscar as cotações de todos os dias. Intervalos maiores podem gerar erros e NaN. Usar a yfinance

ticker_open = yf.download(tickers, start='2012-01-01', end='2022-01-01', interval='1d')['Open']

[*********************100%***********************]  6 of 6 completed

In [23]:
# TASK 10 - Inserir uma coluna representando o "Ano" indicado pelo index

ticker_open['Ano'] = pd.to_datetime(ticker_open.index).strftime('%Y')
ticker_open

,ABEV3.SA,BBDC4.SA,ITUB4.SA,PETR4.SA,VALE3.SA,WEGE3.SA,Ano
Date,,,,,,,
2012-01-02,10.890463,11.047153,15.581813,21.510000,39.770000,2.816568,2012
2012-01-03,10.892461,10.975881,15.518065,21.830000,41.150002,2.775147,2012
2012-01-04,10.716583,11.114862,15.750290,22.180000,42.189999,2.825443,2012
2012-01-05,10.362828,11.047153,15.732076,22.389999,42.509998,2.810650,2012
2012-01-06,10.288879,11.186134,15.845912,22.469999,42.299999,2.893491,2012
...,...,...,...,...,...,...,...
2021-12-23,15.400000,17.500000,21.330000,28.330000,79.949997,33.889999,2021
2021-12-27,15.550000,17.618181,21.480000,28.320000,78.870003,33.470001,2021
2021-12-28,15.540000,17.736362,21.629999,29.010000,78.510002,33.209999,2021
2021-12-29,15.550000,17.681818,21.530001,28.700001,76.379997,33.400002,2021
2021-12-30,15.580000,17.627272,21.440001,28.549999,77.989998,32.919998,2021

In [24]:
# TASK 11 - Tabela dinâmica pegando apenas o primeiro valor observado de cada ano (algo similar a remover duplicatas duplicatas)

tab_dinamica_open = ticker_open.pivot_table(index='Ano',aggfunc='first')
tab_dinamica_open

       ABEV3.SA   BBDC4.SA   ITUB4.SA   PETR4.SA   VALE3.SA   WEGE3.SA
Ano
2012  10.890463  11.047153  15.581813  21.510000  39.770000   2.816568
2013  16.980267  12.764808  15.481638  19.990000  43.000000   4.032544
2014  17.298409  11.383557  15.797645  17.150000  35.910000   4.621301
2015  16.139999  13.621853  18.870523   9.990000  21.700001   5.923076
2016  17.730000   8.946911  15.709090   6.570000  12.490000   5.715384
2017  16.340000  14.886588  22.299999  14.640000  25.280001   5.923076
2018  21.330000  19.380507  28.533333  16.190001  40.439999   9.365384
2019  15.400000  24.198597  35.439999  22.549999  50.009998   8.810000
2020  18.860001  27.445530  37.279999  30.510000  53.980000  17.450001
2021  15.790000  22.752066  31.980000  28.650000  89.349998  37.924999

Agora que temos a soma dividendos e preço de abertura, usamos a fórmula do Dividend Yield (DY) para cada ano. Relembrando...

Dividend Yield (DY %) = Dividendos por ação / Preço da ação * 100

OBS: Utilizamos a soma dos dividendos e JCP entre janeiro e dezembro de cada ano por ação, dividido pelo preço de abertura da no primeiro dia de pregão do respectivo ano

In [25]:
# TASK 12 - Como as duas tabelas estão simétricas, posso simplesmente dividir uma pela outra

tabela_DY_anual = tab_dinamica_dividendos/tab_dinamica_open
tabela_DY_anual

symbol  ABEV3.SA  BBDC4.SA  ITUB4.SA  PETR4.SA  VALE3.SA  WEGE3.SA
Ano
2012    0.043769  0.031959  0.033600  0.023324  0.056872  0.025945
2013    0.015146  0.026388  0.032412  0.019318  0.022899  0.024830
2014    0.034337  0.044674  0.033948  0.056397  0.052625  0.026668
2015    0.097893  0.047875  0.047950  0.000000  0.044948  0.025348
2016    0.036097  0.076410  0.067706  0.000000  0.013314  0.025309
2017    0.033048  0.047428  0.044810  0.000000  0.052432  0.023230
2018    0.025785  0.036907  0.069063  0.056613  0.048686  0.016860
2019    0.031857  0.085140  0.051238  0.041790  0.028282  0.019320
2020    0.021935  0.020906  0.020924  0.000045  0.044600  0.012447
2021    0.043084  0.041490  0.028352  0.197320  0.163946  0.011154

Podemos transpor o dataframe e classificar para um ano desejado

In [26]:
# TASK 13 - Fazer o transposto da tabela de DY anual e ordenar os valores pelo ano de 2021

tabela_DY_anual = tabela_DY_anual.transpose()

tabela_DY_anual = tabela_DY_anual.sort_values(by = '2021', ascending=False)

tabela_DY_anual

Ano,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
symbol,,,,,,,,,,
PETR4.SA,0.023324,0.019318,0.056397,0.000000,0.000000,0.000000,0.056613,0.041790,0.000045,0.197320
VALE3.SA,0.056872,0.022899,0.052625,0.044948,0.013314,0.052432,0.048686,0.028282,0.044600,0.163946
ABEV3.SA,0.043769,0.015146,0.034337,0.097893,0.036097,0.033048,0.025785,0.031857,0.021935,0.043084
BBDC4.SA,0.031959,0.026388,0.044674,0.047875,0.076410,0.047428,0.036907,0.085140,0.020906,0.041490
ITUB4.SA,0.033600,0.032412,0.033948,0.047950,0.067706,0.044810,0.069063,0.051238,0.020924,0.028352
WEGE3.SA,0.025945,0.024830,0.026668,0.025348,0.025309,0.023230,0.016860,0.019320,0.012447,0.011154

In [27]:
# TASK 14 - Trazer o valor acumulado dos dividendos ao longo desses anos, usar um metodo de soma cumulativa

tabela_DY_acumulado_anual = tabela_DY_anual.copy()

tabela_DY_acumulado_anual = tabela_DY_acumulado_anual.transpose().sort_index(axis=1).cumsum()*100

tabela_DY_acumulado_anual

symbol   ABEV3.SA   BBDC4.SA   ITUB4.SA   PETR4.SA   VALE3.SA   WEGE3.SA
Ano
2012     4.376894   3.195900   3.360020   2.332404   5.687201   2.594505
2013     5.891452   5.834679   6.601182   4.264219   7.977085   5.077553
2014     9.325178  10.302043   9.995948   9.903870  13.239614   7.744356
2015    19.114522  15.089593  14.790971   9.903870  17.734411  10.279120
2016    22.724223  22.730633  21.561579   9.903870  19.065828  12.810044
2017    26.028997  27.473405  26.042593   9.903870  24.309040  15.133093
2018    28.607524  31.164088  32.948902  15.565160  29.177668  16.819111
2019    31.793239  39.678098  38.072660  19.744145  32.005830  18.751120
2020    33.986770  41.768708  40.165096  19.748599  36.465834  19.995784
2021    38.295193  45.917716  43.000299  39.480648  52.860411  21.111144