In [1]:
import pandas as pd
import requests
import zipfile

pd.options.display.float_format = '{:.4f}'.format

# Código completo na descrição

In [2]:
ano = "2022"
mes = "12"
url = f'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{ano}{mes}.zip'

In [3]:
download = requests.get(url)

with open(f"inf_diario_fi_{ano}{mes}.zip", "wb") as arquivo_cvm:

    arquivo_cvm.write(download.content) 
    
arquivo_zip = zipfile.ZipFile(f"inf_diario_fi_{ano}{mes}.zip")

In [4]:
dados_fundos = pd.read_csv(arquivo_zip.open(arquivo_zip.namelist()[0]), sep = ";", encoding = 'ISO-8859-1')

dados_fundos

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2022-12-01,1093517.0000,30.6738,1097086.4800,0.0000,0.0000,1
1,FI,00.017.024/0001-53,2022-12-02,1094076.5800,30.6872,1097567.8900,0.0000,0.0000,1
2,FI,00.017.024/0001-53,2022-12-05,1094638.6700,30.7007,1098050.7100,0.0000,0.0000,1
3,FI,00.017.024/0001-53,2022-12-06,1095200.3400,30.7143,1098536.0700,0.0000,0.0000,1
4,FI,00.017.024/0001-53,2022-12-07,1095464.0200,30.7279,1099020.9400,0.0000,0.0000,1
...,...,...,...,...,...,...,...,...,...
539740,FI,97.929.213/0001-34,2022-12-26,76684544.1700,10.0909,76683936.6200,0.0000,0.0000,2
539741,FI,97.929.213/0001-34,2022-12-27,76630935.4600,10.0896,76673974.5500,0.0000,0.0000,2
539742,FI,97.929.213/0001-34,2022-12-28,76731693.0600,10.1110,76836557.3700,0.0000,0.0000,2
539743,FI,97.929.213/0001-34,2022-12-29,67616216.4800,10.1302,76982947.6800,0.0000,0.0000,2
539744,FI,97.929.213/0001-34,2022-12-30,67700060.7600,10.1412,77066406.2100,0.0000,0.0000,2

In [5]:
dados_cadastro = pd.read_csv('https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv', 
                             sep = ";", encoding = 'ISO-8859-1')

dados_cadastro = dados_cadastro[['CNPJ_FUNDO', 'DENOM_SOCIAL']]

dados_cadastro = dados_cadastro.drop_duplicates()

dados_cadastro

C:\Users\rmnf\AppData\Local\Temp\ipykernel_6900\3548788005.py:1: DtypeWarning: Columns (14,17,18,20,22,24,27,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  dados_cadastro = pd.read_csv('https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv',

               CNPJ_FUNDO                                       DENOM_SOCIAL
0      00.000.684/0001-21  DEUTSCHE BANK FDO APLIC QUOTAS FDO INV FINANCE...
1      00.000.731/0001-37  ITAMARITI CASH FUNDO APLICACAO QUOTAS FDOS INV...
2      00.000.732/0001-81  FUNDO APLIC. QUOTAS DE F.I. SANTANDER CURTO PRAZO
3      00.000.740/0001-28  FUNDO DE APLIC EM QUOTAS DE FUNDOS DE INV BMC ...
4      00.000.749/0001-39  BALANCE FUNDO APLICACAO QUOTAS FUNDO INVESTIME...
...                   ...                                                ...
71321  28.850.140/0001-78  FUNDO DE FINANCIAMENTO DA INDUSTRIA CINEMATOGR...
71322  28.912.043/0001-62  HAPVIDA - FUNDO DE FINANCIAMENTO DA INDUSTRIA ...
71323  31.674.280/0001-47  MEDIA VENTURE ESG INCENTIVADO - FUNDO DE FINAN...
71324  32.222.962/0001-81  Fundo de Financiamento da Indústria Cinematogr...
71325  48.879.897/0001-00  FUNDO DE  FINANCIAMENTO DA INDÚSTRIA CINEMATOG...

[62774 rows x 2 columns]

In [6]:
data_inicio_mes = (dados_fundos['DT_COMPTC'].sort_values(ascending = True).unique())[0]
data_fim_mes = (dados_fundos['DT_COMPTC'].sort_values(ascending = True).unique())[-1]
        

dados_fundos_filtrado = dados_fundos[(dados_fundos['DT_COMPTC'].isin([data_inicio_mes, data_fim_mes]))]
                           

dados_fundos_filtrado

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2022-12-01,1093517.0000,30.6738,1097086.4800,0.0000,0.0000,1
21,FI,00.017.024/0001-53,2022-12-30,1101258.2300,30.9604,1104335.8500,0.0000,0.0000,1
22,FI,00.068.305/0001-35,2022-12-01,37405993.1800,31.2611,37396214.9000,0.0000,11395.6300,6325
43,FI,00.068.305/0001-35,2022-12-30,37280307.1800,31.5733,37267073.4300,0.0000,0.0000,6300
44,FI,00.071.477/0001-68,2022-12-01,4050002808.7500,11.2531,4049571299.6300,3243205.1400,30019263.2200,69175
...,...,...,...,...,...,...,...,...,...
539700,FI,97.711.801/0001-05,2022-12-30,84865166.6800,2.8370,84832927.1800,0.0000,0.0000,1
539701,FI,97.929.197/0001-80,2022-12-01,149377359.9700,4.8505,149244317.3700,0.0000,0.0000,13
539722,FI,97.929.197/0001-80,2022-12-30,142648863.0800,4.6320,142519765.4300,0.0000,0.0000,13
539723,FI,97.929.213/0001-34,2022-12-01,76260364.6700,10.0330,76243918.8900,0.0000,0.0000,2
539744,FI,97.929.213/0001-34,2022-12-30,67700060.7600,10.1412,77066406.2100,0.0000,0.0000,2

In [7]:
base_final = pd.merge(dados_fundos_filtrado, dados_cadastro, how = "left", 
                      left_on = ["CNPJ_FUNDO"], right_on = ["CNPJ_FUNDO"])

base_final = base_final[['CNPJ_FUNDO', 'DENOM_SOCIAL', 'DT_COMPTC', 'VL_QUOTA', 'VL_PATRIM_LIQ', 'NR_COTST']]

base_final

,CNPJ_FUNDO,DENOM_SOCIAL,DT_COMPTC,VL_QUOTA,VL_PATRIM_LIQ,NR_COTST
0,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,2022-12-01,30.6738,1097086.4800,1
1,00.017.024/0001-53,FUNDO DE INVESTIMENTO RENDA FIXA EXPONENCIAL,2022-12-30,30.9604,1104335.8500,1
2,00.068.305/0001-35,FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE IN...,2022-12-01,31.2611,37396214.9000,6325
3,00.068.305/0001-35,FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE IN...,2022-12-30,31.5733,37267073.4300,6300
4,00.071.477/0001-68,BB RENDA FIXA AUTOMÁTICO EMPRESA SIMPLES FUNDO...,2022-12-01,11.2531,4049571299.6300,69175
...,...,...,...,...,...,...
49075,97.711.801/0001-05,953 FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS D...,2022-12-30,2.8370,84832927.1800,1
49076,97.929.197/0001-80,LECT FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS ...,2022-12-01,4.8505,149244317.3700,13
49077,97.929.197/0001-80,LECT FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS ...,2022-12-30,4.6320,142519765.4300,13
49078,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,2022-12-01,10.0330,76243918.8900,2
49079,97.929.213/0001-34,WHG SISTEMA II FUNDO DE INVESTIMENTO MULTIMERC...,2022-12-30,10.1412,77066406.2100,2

In [9]:
fundos_prev = base_final[base_final['DENOM_SOCIAL'].str.contains("PREV", na = False)]
fundos_prev = fundos_prev[fundos_prev.VL_PATRIM_LIQ >= 10000000000]
#fundos_prev = fundos_prev[fundos_prev.NR_COTST == 1]
fundos_prev = fundos_prev.sort_values(by="VL_PATRIM_LIQ", ascending=False)

fundos_prev

,CNPJ_FUNDO,DENOM_SOCIAL,DT_COMPTC,VL_QUOTA,VL_PATRIM_LIQ,NR_COTST
3731,07.593.972/0001-86,BRASILPREV TOP TPF FUNDO DE INVESTIMENTO RENDA...,2022-12-30,5.3283,139961978951.5300,270
3730,07.593.972/0001-86,BRASILPREV TOP TPF FUNDO DE INVESTIMENTO RENDA...,2022-12-01,5.2738,138632076242.3200,280
1232,03.737.219/0001-66,FUNDO DE INVESTIMENTO PREVIDENCIÁRIO CAIXA PRE...,2022-12-01,5.4373,56624375626.5600,9
1233,03.737.219/0001-66,FUNDO DE INVESTIMENTO PREVIDENCIÁRIO CAIXA PRE...,2022-12-30,5.4942,56581705709.9600,9
3494,07.187.548/0001-31,BRADESCO FUNDO DE INVESTIMENTO RENDA FIXA MÁST...,2022-12-01,5.3663,48189175546.2700,35
...,...,...,...,...,...,...
1240,03.737.224/0001-79,FUNDO DE INV EM COTAS DE FUNDOS DE INV PREVIDE...,2022-12-01,6.5296,10194142952.5100,1
1241,03.737.224/0001-79,FUNDO DE INV EM COTAS DE FUNDOS DE INV PREVIDE...,2022-12-30,6.5925,10181239842.1700,1
13092,18.630.011/0001-10,BRASILPREV RT CLÁSSICO FUNDO DE INVESTIMENTO E...,2022-12-30,1.9908,10124140647.4200,1
7066,11.060.657/0001-60,FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE IN...,2022-12-01,2.1055,10119601732.2100,1
7067,11.060.657/0001-60,FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE IN...,2022-12-30,2.1249,10063360273.6000,1

# Patrimônio e performance do fundo em dezembro

In [12]:
maior_fundo = fundos_prev[(fundos_prev['CNPJ_FUNDO'] == "07.593.972/0001-86") &
                                          ( fundos_prev['DT_COMPTC'] == "2022-12-30")]

patrimonio_do_fundo =  "R$ " + str((maior_fundo['VL_PATRIM_LIQ'].iloc[0]/1000000000).round(2)) + " Bi"

patrimonio_do_fundo

'R$ 139.96 Bi'

In [13]:
maior_fundo_mes = fundos_prev[(fundos_prev['CNPJ_FUNDO'] == "07.593.972/0001-86")]
                                          
retorno_dez = ("Retorno fundo: " +
            str(((maior_fundo_mes['VL_QUOTA'].iloc[-1]/maior_fundo_mes['VL_QUOTA'].iloc[0] - 1)
                 * 100).round(2)) 
               + "%") 
    
retorno_dez

'Retorno fundo: -1.02%'